name=IS66_RAM_library
version=0.1.0
author=Mark Stanley
maintainer=Community https://github.com/Nullkraft/IS66_RAM_library
sentence=IS66WVS4M8ALL 32Mb SerialRAM driver library
paragraph=Read and write functions are provided at the highest level. You can select the address and read and write your data
category=DataStorage
url=https://github.com/Nullkraft/IS66_RAM_library
architectures=*
